#docker-compose.yml
networks:
  ext-net:
  int-net:

services:
  web-server:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: whamll_web
    ports:
      - "8080:8080"
      - "2222:22"
    networks:
      - ext-net
      - int-net
    depends_on:
      db-server:
        condition: service_healthy
    volumes:
      - web_uploads:/usr/local/tomcat/webapps/ROOT/uploads
    env_file:
      - .env
    environment:
      - API_SERVER_URL=${API_SERVER_URL}
    restart: always

  api-server:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: whmall_api
    ports:
      - "8081:8081"
    volumes:
      - api_uploads:/tmp/uploads
    networks:
      - int-net
    depends_on:
      db-server:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  db-server:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: whmall_oracle
    networks:
      - int-net
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./data/db/init.sql:/container-entrypoint-initdb.d/init.sql
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - ORACLE_CHARACTERSET=AL32UTF8
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/${ORACLE_PASSWORD}@localhost/XEPDB1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
