version: '3.8'

networks:
  dmz-net:
  int-net:

services:
  web-server:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dmz-net
      - int-net
    depends_on:
      - api-server
    volumes:
      - uploads:/var/www/html/uploads
    env_file:
      - .env
    environment:
      - API_SERVER_URL=${API_SERVER_URL}

  api-server:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - int-net
    depends_on:
      - db-server
    volumes:
      - uploads:/tmp/uploads
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

  db-server:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    # 외부 포트 노출 차단 (내부망 전용)
    networks:
      - int-net
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=login_db

volumes:
  mysql_data:
  uploads: