version: '3.8'

networks:
  dmz-net:
  int-net:

services:
  web-server:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dmz-net
      - int-net
    depends_on:
      - api-server
    volumes:
      - uploads:/var/www/html/uploads
    environment:
      - API_SERVER_URL=http://api-server:8081

  api-server:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - int-net
    depends_on:
      - db-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-server:3306/login_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    volumes:
      - uploads:/tmp/uploads

  db-server:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - int-net
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=login_db

volumes:
  mysql_data:
  uploads: 