#docker-compose.yml
networks:
  ext-net:
  int-net:

services:
  web-server:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: whamll_web
    ports:
      - "8080:8080"
      - "2222:22"
    networks:
      - ext-net
      - int-net
    depends_on:
      db-server:
        condition: service_healthy
    volumes:
      - web_uploads:/usr/local/tomcat/webapps/ROOT/uploads
    env_file:
      - .env
    environment:
      - API_SERVER_URL=${API_SERVER_URL}
    restart: always
    command: /bin/sh -c "sleep 300 && catalina.sh run"

  api-server:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: whmall_api
    ports:
      - "8081:8081"
    volumes:
      - api_uploads:/tmp/uploads
    networks:
      - int-net
    depends_on:
      db-server:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    command: /bin/sh -c "sleep 300 && java -jar /app/app.jar"

  db-server:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: whmall_oracle
    networks:
      - int-net
    ports:
      - "1522:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./data/db/init.sql:/container-entrypoint-initdb.d/init.sql:ro
    environment:
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF; SELECT COUNT(*) FROM all_tables WHERE owner=UPPER(\'${SPRING_DATASOURCE_USERNAME}\') AND table_name=\'RANKS\'; EXIT;' | sqlplus -s ${SPRING_DATASOURCE_USERNAME}/${SPRING_DATASOURCE_PASSWORD}@localhost/freepdb1 | grep 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  oracle_data:
  web_uploads:
  api_uploads: